WeTransfer/WeTransfer-iOS-CI

- Danger/Dangerfile
This will show Danger reports more often, even if tests fail to run 🎉 
Fixes #8 
Fixes #9
> Capture errors in code coverage

- Danger/Dangerfile
- Fastlane/Fastfile
We can now create multiple test summaries including coverage reports by passing:
```ruby
validate_changes(project_name: options[:project_name], xcov_targets: "Rabbit.framework, Networking.framework")
```
Also, by running multiple scans and saving reports as separated file names:
```ruby
ENV["XCPRETTY_JSON_FILE_OUTPUT"] = "build/reports/Networking_Tests.json"
scan(
scheme: "Networking",
project: "Vendor/Networking/Networking.xcodeproj",
device: "iPhone 8",
clean: true,
code_coverage: true,
formatter: "xcpretty-json-formatter"
)
ENV["XCPRETTY_JSON_FILE_OUTPUT"] = "build/reports/Rabbit_Tests.json"
scan(
scheme: options[:project_name],
project: "#{options[:project_name]}.xcodeproj",
device: "iPhone 8",
clean: true,
code_coverage: true,
formatter: "xcpretty-json-formatter"
)
```
> Add the possibility to apply multiple targets

- spec/spec_helper.rb
We had some fake data sitting in the spec_helper that was causing false positives when security researchers ran scans. Now it's more obviously fake which will cut down on duplicate reports.
> Make fake data more obviously fake

- Danger/Dangerfile
Instead of:
<table>
<thead>
<tr>
<th width="50"></th>
<th width="100%" data-danger-table="true" data-kind="Message">
4 Messages
</th>
</tr>
</thead>
<tbody>
<tr>
<td>:book:</td>
<td data-sticky="false">Coyote Tests:</td>
</tr>
<tr>
<td>:book:</td>
<td data-sticky="false">Executed 513 tests, with 2 failures (0 unexpected) in 96.910 (97.478) seconds</td>
</tr>
<tr>
<td>:book:</td>
<td data-sticky="false">Okapi Tests:</td>
</tr>
<tr>
<td>:book:</td>
<td data-sticky="false">Executed 21 tests, with 0 failures (0 unexpected) in 0.116 (0.134) seconds</td>
</tr>
</tbody>
</table>
It will now be:
<table>
<thead>
<tr>
<th width="50"></th>
<th width="100%" data-danger-table="true" data-kind="Message">
4 Messages
</th>
</tr>
</thead>
<tbody>
<tr>
<td>:book:</td>
<td data-sticky="false">Coyote Tests: …
> Make messages nicer for multiple project testing

- SwiftLint/.swiftlint-source.yml
Allowing force unwraps checks. They can be used in some cases and be used as fatalErrors.
> Remove force unwrap checks

- Danger/ext/git_swift_linter.rb
- spec/git_swift_linter_spec.rb
No more need to put #trivial everywhere 🎉 
Also, makes sure a changelog is required for string file changes.
Fixes #31 
Fixes #32
> Only warn for changelog entry if target branch is develop or master

- Danger/Dangerfile
- SwiftLint/.swiftlint-source.yml
See [https://github.com/orta/danger-junit](https://github.com/orta/danger-junit) for more info.
I've also updated our SwiftLint rules to be more in line with how we work. We've had some warnings for quite some time already, which made me think that the threshold was too restricted for us. I've also looked at the code and concluded that it would take a lot of effort to change it to the requirements of SwiftLint and therefore, changing our threshold a bit felt better!
> Use JUnit and Trainer for test reporting, Update SwiftLint rules

- Danger/Dangerfile
- Fastlane/Fastfile
Danger is running in verbose mode now which hides a lot of unnecessary logs.
Also, we now filter out duplicate code coverage reports. It could happen that a parent project runs tests and creates coverage for a child framework because it's hitting that code as well. This turns into a very low code coverage because it's obviously not testing the full framework.
We fixed this by only showing the top-level code coverage report.
> Turns on verbose for Danger, prevent duplicate coverage reports

- Danger/Dangerfile
- Danger/ext/git_swift_linter.rb
- spec/git_swift_linter_spec.rb
This adds an HTML Link to the Bitrise build to quickly access the build that has run.
It does not entirely fix the linked issue but linking the logs directly was a bit harder to do.
Fixes #38
> Add a link towards the Bitrise build for quick access

- Fastlane/Fastfile
This moves all the logic from Coyote into this repository for:
It's already used by Coyote and it will allow us to easily generate open-source releases soon.
> Add lanes for changelog generation & release creation

- Bitrise/tag_releasing_bitrise.yml
- Bitrise/testing_bitrise.yml
Changing the Bitrise.yml to only update the WeTransfer-iOS-CI submodule remotely as well after experiencing issues in Coyote.
> Only update the CI submodule remotely

- Changelog.md
Containing all the changes for our [**3.1.0 Release**](Warning: Permanently added 'github.com,140.82.114.3' (RSA) to the list of known hosts.
Result of creating the release:
Fetching tags
Latest tag is 3.1.0
Tag 3.1.0 is created at 2020-02-07 14:46:37 +0100
Creating a changelog between tag 3.0.0 and 3.1.0
Tag 3.0.0 is created at 2020-01-28 15:29:20 +0100
Getting all changes since 3.0.0
Creating a release for tag 3.1.0 at repository WeTransfer/WeTransfer-iOS-CI
Marking PR #57 as having been released in version #3.1.0
Marking PR #56 as having been released in version #3.1.0
Successfully posted comment at: https://github.com/WeTransfer/WeTransfer-iOS-CI/pull/57#issuecomment-583404623
Successfully posted comment at: https://github.com/WeTransfer/WeTransfer-iOS-CI/pull/56#issuecomment-583404624 …
> Merge release 3.1.0 into master

- SwiftLint/.swiftlint-tests.yml
Disables the `weak_delegate` for SwiftLint in the test target. This rule often leads to false positives when defining a property that holds a reference to a delegate like this: 
```
private var mockDelegate: MockDelegate!
fun setup() {
...
}
```
> Disable weak delegate rule in test target

- Changelog.md
Containing all the changes for our [**3.2.0 Release**](https://github.com/WeTransfer/WeTransfer-iOS-CI/releases/tag/3.2.0).
> Merge release 3.2.0 into master

- SwiftLint/.swiftlint-tests.yml
- SwiftLint/swiftlint.sh
I've been using https://dev.to/jonatanlllima/drops-3-swift-swiftlint-e-swiftformat-1b34 and looked a lot at https://github.com/realm/SwiftLint/issues/413 to see whether we could improve our SwiftLint implementation. Right now, we were linting _all files_ in _all frameworks_ easily adding up ~12 seconds per incremental build. 
In other words, an incremental build in my test case went from 23.4 seconds to 9.9 seconds 🚀
> Only lint files that are changed

- Bitrise/testing_bitrise.yml
- Danger-Swift/Sources/WeTransferPRLinter/XcodeSummaryReporter.swift
By ignoring the `SourcePackages` folder path we ignore the warnings from SPM.
> Ignore warnings in SwiftPM

- Bitrise/testing_bitrise.yml
- Fastlane/Fastfile
After spending time investigating our current workflow in Bitrise, I've found several ways of how we could improve our pipeline.
> Optimise Bitrise runs

- Fastlane/deployment_lanes.rb
- Scripts/test_setup.sh
To run our tests in BrowserStack devices, should push a dev ipa file to their cloud
This will result in a URL unique to this ipa, that can be consumed later in test frameworks.
The first stage of this PR makes a dev build ready to be uploaded to browserstack 
This lane will later be used in the Bitrise for Appium workflow
> Build dev ipa for sending to browser stack

- Fastlane/deployment_lanes.rb
For .ipa artefacts for appium tests, the build shall be signed with dev certificates
> Sign with development certificate

- Fastlane/deployment_lanes.rb
We were in a situation where we haven't released a new version for a while and created a lot of app store release candidates since the last release. As the GH api releases endpoint is paginated with a default page size of 30 the response didn't contain the latest non release tag. If we would support pagination it would be returned on page 2. However, the easiest fix at this time is to simply set the page size to the max (100). It is unlikely that within our current release process we will exceed this number.
> Increase the page size of the fetch GH releases command.

- SwiftLint/.swiftlint-source.yml
- SwiftLint/.swiftlint-tests.yml
Since we're only linting changed files, depending on Swiftlint for TODOs is not sufficient. Therefore, we decided to use #warning("TODO: ..") instead, so we will always have a warning visible within Xcode telling us about a TODO.
Though, we need to disable the rule in SwiftLint to prevent duplicate warnings.
> Disable todo rule in Swiftlint

- Bitrise/testing_bitrise.yml
- Fastlane/Fastfile
It turned out that the `build-for-testing` script runs faster when executed manually. The other testing projects were slower when using `xcodebuild` directly, so lets use it only for build for testing.
> Run build for testing w/o scan

- Fastlane/Fastfile
New in Xcode 13 is the option to retry a test on failure. This can be a great way to reduce the number of flaky tests.
Fixes #96
> Retry tests on failure

- BuildTools/swiftformat.sh
- BuildTools/swiftlint.sh
The precommit hook failed. Exporting the PATH was indeed the fix, but to a different location.
This was caused due to the fact that I had `mint` installed on my previous non-M1 Mac, which installed the brew packages to a different directory than it would with a fresh install. More context [here](https://apple.stackexchange.com/questions/410825/apple-silicon-port-all-homebrew-packages-under-usr-local-opt-to-opt-homebrew)
Therefore, we're now both supporting `/opt/homebrew/bin` (new) and `/usr/local/bin` (old)
> Update PATH to correct location

- WeTransferPRLinter/Sources/WeTransferPRLinter/XCResultReporting/ResultItems/IssueSummaries.swift
- WeTransferPRLinter/Sources/WeTransferPRLinter/XCResultReporting/ResultItems/TestSummaries.swift
- WeTransferPRLinter/Tests/WeTransferPRLinterTests/XCResultSummaryReporterTests.swift
Since we're going to use skipping tests for flaky/failing tests, we should report these into Danger as well.
Example:
`**PRLinterViewModelTests/testSkippedExample():**<br/>PRLinterAppTests.swift:32 Test skipped - This test should be skipped`
And summary:
`PRLinterAppTests: Executed 10 tests (1 failed, 1 retried, 1 skipped) in 0.097 seconds`
Fixes #107
> [Danger] Report skipped tests

- BuildTools/.swiftlint-source.yml
It was causing some test file within the SDK's `SPMDependencyResolver` tests to trigger a long file warning, specifically PackageJSON.swift which is auto generated it seems.
> Add `${SRCROOT}/*/Tests` to excluded paths in `swiftlint-source.yml`

- BuildTools/swiftformat.sh
Since we're all on ARM macs either way. This solves an issue I had with SourceTree in relationship to precommit hooks:
> Always export path for ARM

- Bitrise/testing_bitrise.yml
Draft PRs are likely to receive updates, which means that the CI run is not valuable. In other words; you'll do a new CI run either way, so it's better to skip CI right away and save build credits.
The status check will fail right away. There's currently no other way of doing this, as it would've been ideal to not even run Bitrise for draft PRs. Though, for the time being, this will be a good solution. More context on the Bitrise blog: https://blog.bitrise.io/post/skip-certain-builds-or-only-some-steps-with-the-draft-pr-env-var
Also, if you've been using draft PRs to get early CI results, it's likely better to just run Bitrise locally or run tests locally.
Fixes #118
> Skip running CI for draft PRs

- Fastlane/deployment_lanes.rb
Once https://github.com/WeTransfer/GitBuddy/pull/74 is merged, we can delete GitHub releases and matching tags using GitBuddy.
This PR configures the command and deletes 1 pre-release per time, so we can test out the logic in production. I've already tested the logic locally, both through the terminal and unit tests. Yet, I want to slowly enable this to prevent us from deleting tags unexpectedly.
This is also the last part of #86.
Fixes #86
> Delete pre-release tags after a successful release

- Fastlane/deployment_lanes.rb
Our setup should've already been correct for releasing the submitted builds to QA. Yet, it didn't work, so I added some extra logging so we can hopefully find out later.
I've also added an extra note to the changelog to make it clearer for QA that a build was submitted.
Fixes #125
> Add extra note about a released build

- Fastlane/Fastfile
By always using fastlane I'm hoping for us to get better feedback through Danger in cases a build error occurs.
Fixes [TMI-54]
Fixes https://github.com/WeTransfer/WeTransfer-iOS-CI/issues/127
[TMI-54]: https://wetransfer.atlassian.net/browse/TMI-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Make sure to use fastlane for running SPM testing

- Fastlane/Fastfile
Rethrowing errors can be a way to know whether tests failed or not at the implementation level.
> Allow rethrowing errors

- Bitrise/testing_bitrise.yml
No need to run tests when there are only translations returned by Smartling.
> Skip CI for translation branches

- Fastlane/Fastfile
- Fastlane/deployment_lanes.rb
With version 0.17.0 of mint it is required to add `~/.mint` to your $PATH to make it possible to access installed tools globally, or alternatively prepend your command with `mint/run`.
> Use mint run to run the gitbuddy command

- Fastlane/Fastfile
- Fastlane/deployment_lanes.rb
Reverts WeTransfer/WeTransfer-iOS-CI#138
We can't use `mint run` since that changes the output and we expect the output to be valid JSON.
we can use `mint run --silent` instead, I'll open a PR for that https://github.com/WeTransfer/WeTransfer-iOS-CI/pull/140
> Revert "Use mint run to run the gitbuddy command"

- Fastlane/deployment_lanes.rb
Fixes a mistake where we were using branch name while it was not defined yet.
We'll now first check if we can use the Bitrise branch name and fall back to develop if the environment doesn't contain this variable.
> Fix beta build delivery

- Bitrise/testing_bitrise.yml
- BuildTools/Mintfile
The workflow is changed to now deliver the `xcresult` file as build artifact. If the `xcresult` file doesn't exist, the step will silently fail since it's marked as `skippable`. I decided to only upload the `xcresult` file to keep our CI runs as performant as possible.
I've also removed the version lock on SwiftFormat and SwiftLint since my commits were constantly trying to downgrade my local installed SwiftFormat. I also think it's better to keep them up to date with latest version. Let me know if you disagree!
> Deliver `xcresult` file as build artifact

- Fastlane/shared_lanes.rb
- Package.resolved
- WeTransferPRLinter/Sources/WeTransferPRLinter/WeTransferPRLinter.swift
- WeTransferPRLinter/Sources/WeTransferPRLinter/XCResultReporting/Extensions/Danger+XCResultItemReporting.swift
- WeTransferPRLinter/Sources/WeTransferPRLinter/XCResultReporting/ResultItems/IssueSummaries.swift
- WeTransferPRLinter/Tests/WeTransferPRLinterTests/XCResultSummaryReporterTests.swift
See this issue for more context: https://github.com/danger/swift/issues/513#issuecomment-1099137770
Basically; after GH introduced [their new PR experience](https://github.com/github/feedback/discussions/12341), things started to break on our side. The ability to report errors and warnings inline seems to be broken, so I temporarily disabled this feature for now.
Testing and debugging Danger can be difficult sometimes, so I decided to create a `fastlane run_danger_locally` lane which simplifies this by a lot.
Fixes #145
> Disable file and line reporting to fix Danger warning and error reports

- Fastlane/Fastfile
By cleaning the local reports we prevent CI from failing when running locally for testing purposes
> Clear local reports before running new tests

- Fastlane/Fastfile
We configured the build log twice which also broke the artifact delivery for build logs.
> Remove duplicate build log setting

- BuildTools/.swiftlint.yml
- WeTransferPRLinter/Sources/WeTransferPRLinter/WeTransferPRLinter.swift
This PR updates the warnings for emitting the mark warning and update the `type_body_length` rule.
> SwiftLint warnings

- Bitrise/tag_releasing_bitrise.yml
- Fastlane/deployment_lanes.rb
This PR will basically change the following things:
- Introducing a `next` in case nothing has changes since the last tag was created (This change updated the indention across a few lines, so sorry for the messy code review in these lines 😞).
- We removed a few parameters from the TestFlight call because they were set to default values anyway (`skip_waiting_for_build_processing` and `skip_submission`).
- The log will now explicitly mention the next build version that's on its way.
- `puts` calls were replaced with `UI.message`.
- `sh` calls were unified.
- We'll have a `UI.success` message at the end of a beta build.
- The changelog is now safely truncated at 3900 characters (4000 being Apples limit).
- A helper method was added to check if we are building on CI.
> [No Ticket]: Refactoring fastlane script

- Fastlane/deployment_lanes.rb
We used to pass in the `up-until-tag` into GitBuddy, which didn't work since the tag was not fetched locally yet. Instead, we can use GitBuddy's ability to fetch the latest tag. To do so, we need to remove passing in any tag.
> Don't pass the tag name to use the latest tag instead for GitBuddy Deletion

- Fastlane/deployment_lanes.rb
- Fastlane/helper.rb
- Fastlane/shared_lanes.rb
This PR will introduce a new helper method (slack_message) to easier send out more clearly communicated slack messages.
Not needed informations will no longer be broadcasted and a clear difference between the different types on message contexts will be added.
Additionally we'll add support for more message payloads in case there is more to say (error handling PR will be opened on Mule).
> Better slack messaging

- Fastlane/deployment_lanes.rb
We were skipping submission in the TestFlight action, withholding builds from being pushed to configured TestFlight groups.
> Ensure delivering release builds to TestFlight groups

- BuildTools/swiftformat.sh
The changes introduced in https://github.com/WeTransfer/WeTransfer-iOS-CI/pull/174 didn't consider the submodules, so for now we're reverting it.
I'll later investigate how we can make sure the submodules changes are also formatted.
> Revert pre-commit change

- Fastlane/deployment_lanes.rb
This PR will rename the following release type titles:
| before | after |
| - | - |
| App Store Release Candidate | Beta |
| App Store Release | Release |
| App Store Hotfix Release | Release (hotfix) |
https://wetransfer.atlassian.net/browse/TMOB-1209
https://wetransfer.slack.com/archives/C3ZV6K8K0/p1655728927908339
> [TMOB-1209]: Name releases (title) more clearly on GitHub

- Fastlane/deployment_lanes.rb
This will actually post errors/issue we have during release on our slack channel and inform us about failing releases.
> Handle errors in release lane

- Fastlane/shared_lanes.rb
`error` objects outside of the fastlane context do not support `error_info`.
We should use the ruby default instead.
> Error handling - method error_info not working

- Fastlane/deployment_lanes.rb
This PR will change the "error" message in case there was no new (beta) version build, due to no changes.
Previously the wording was wrong, because it claimed there has been no changes since the last release version. Actually it was comparing current HEAD to the last_git_tag already.
> Use last_git_tag instead of last release tag

- Bitrise/testing_bitrise.yml
- WeTransferPRLinter/Sources/WeTransferPRLinter/WeTransferPRLinter.swift
- WeTransferPRLinter/Tests/WeTransferPRLinterTests/WeTransferLinterTests.swift
This PR deploys the simulator build to Bitrise and adds the download URL to the PR.
Unfortunately, the download URL is private and you need to log in to Bitrise.
There is [a way](https://gist.github.com/Marchuck/de230ed681428d47ce1276c14788ef9a#file-print_out_artifact_urls-sh) to generate a public URL for artifacts via Bitrise API but the URL expires in 10 minutes. 
Here is [a feature request](https://discuss.bitrise.io/t/expose-url-to-artifact-outside-of-build-page-public-install-page-for-non-app-artifacts-pkg-zip/2330) for permanent artifact download URL on Bitrise
> Deploy Simulator Build

- Fastlane/shared_lanes.rb
Our slack channel started to get very noisy from fastlane errors happening on a local machine.
This PR will focus on CI only.
> Do not report errors happening other than on CI

- Fastlane/deployment_lanes.rb
This PR will fix a tag lookup for the latest non beta release.
Due to a broken naming convention the lookup did not work as expected anymore.
> Fixes Github tag lookup

- Fastlane/deployment_lanes.rb
To create a build artefact for firebase test lab, have to install certificates separately. 
Also I shall be reusing this lane for appium_build lane
> install certificates seperately for xctest builds

- Fastlane/deployment_lanes.rb
`install_certificates` is expecting `options` but there was none defined.
CC: @rajwe
> Fix `install_certificates` lane

- Fastlane/deployment_lanes.rb
Related to [TMOB-1592].
This PR adds an option to pass a branch to the `beta` lane.
[TMOB-1592]: https://wetransfer.atlassian.net/browse/TMOB-1592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add branch option to `beta` lane

- Fastlane/deployment_lanes.rb
Part of [TMOB-1799].
This PR makes sure we only run `prepare_for_ci` if `is_running_on_CI` in the `release` lane. 
[TMOB-1799]: https://wetransfer.atlassian.net/browse/TMOB-1799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Execute `prepare_for_ci` only if `is_running_on_CI`

- Bitrise/tag_releasing_bitrise.yml
Our open-source repos require signed commits, so we have to enable signed commits for our release workflows.
Fixes [TMOB-1933]
[TMOB-1933]: https://wetransfer.atlassian.net/browse/TMOB-1933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Enable signed commits for open source

- Bitrise/testing_bitrise.yml
We used to let a CI run fail for smartling-only branches. However, that means our Danger check doesn't succeed and we're unable to merge in our PRs.
Secondly, unit tests can depend on translations, so we should actually run our suite of tests normally for localization only PRs. Therefore, I've removed the check.
> Remove localization check and run CI normally

- Bitrise/testing_bitrise.yml
We removed the cache directories in [this PR](https://github.com/WeTransfer/WeTransfer-iOS-CI/pull/203/files) since I assumed we didn't need them anymore now that we have an executable for Danger. However, it turns out that we're still fetching packages specifically for the Danger plugins we define inside this repository.
It's not worth optimizing those dependencies into Binary frameworks or such, but we can optimize and benefit from caching at the very least.
> Restore cache paths for Danger

- .gitignore
- Bitrise/testing_bitrise.yml
- Fastlane/testing_lanes.rb
- WeTransferPRLinter/.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
- bitrise.yml
While we introduced this change in [this PR](https://github.com/WeTransfer/WeTransfer-iOS-CI/pull/204/files#diff-1aa9e75b21f987435cd386618fa281f6dde84a921bcd54917e225cb3dd203016R47) to enable us to evaluate SPM separately, it turned out to mess up with Xcode on CI since `xcodebuild` itself wants to resolve packages during the build even though they were already resolved.
It lead to complicated errors, like:
```
sh: line 1:  2361 Abort trap: 6           env NSUnbufferedIO=YES xcodebuild -scheme CoreUIKit -destination ‘platform=iOS Simulator,id=72C3AE83-9A62-4CE8-BCC5-EAA3D56F8FB4’ -derivedDataPath /Users/vagrant/git/build/derived_data -resultBundlePath ‘/Users/vagrant/git/build/reports/CoreUIKit.xcresult’ -disable-concurrent-testing -enableCodeCoverage YES -clonedSourcePackagesDirPath …
```
> See if this fixes CI by fetching packages as part of scan

- Bitrise/Scripts/pr_assignments.sh
- Bitrise/Scripts/pr_labels_testing.sh
- Bitrise/Scripts/setup_environment.sh
- Bitrise/testing_bitrise.yml
- Fastlane/testing_lanes.rb
- bitrise.yml
After we merged in this PR, we can add a `pr-testing` label to any PR which will allow to:
- Run CI as normal under draft
- Use the submodule CI reference instead of updating to latest `master` branch
This will improve our CI testing experience and makes it more clear for reviewers that a PR is work in progress. Before this, we had to open a PR as if it was ready to be reviewed, even though we might wanted to do some CI testing first.
> Introduce a CI Testing mode

- Bitrise/testing_bitrise.yml
- Fastlane/testing_lanes.rb
Fixes #191 
Fixes [TMOB-1600]
[TMOB-1600]: https://wetransfer.atlassian.net/browse/TMOB-1600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add timeout for fastlane test

- Fastlane/testing_lanes.rb
Fixes:
```
[14:13:54]: ▸ xcodebuild: error: The flag -enableCodeCoverage is only supported when testing.
```
> Disable code coverage when build for testing

- BuildTools/Mintfile
See related issue: https://github.com/realm/SwiftLint/issues/4559
pre-commit would fail to install SwiftLint in 0.50.0
> Update SwiftLint to 0.50.1 to fix precommit install

- WeTransferPRLinter/Sources/WeTransferPRLinter/WeTransferPRLinter.swift
- WeTransferPRLinter/Tests/WeTransferPRLinterTests/WeTransferLinterTests.swift
By configuring `disable_danger_swiftlint` environment variable to `true` we can skip SwiftLint executed through Danger. This is useful for our projects that make use of the SwiftLint build tool plugin.
> Allow skipping SwiftLint through Danger

- Fastlane/testing_lanes.rb
Turns out we needed a different Ruby syntax 🙈 
```diff
- ENV.has_value?("DD_API_KEY")
+ ENV.include?("DD_API_KEY")
```
Learning Ruby every day!
> Fix Datadog CI Tracing

- Fastlane/testing_lanes.rb
```diff
- [13:54:51]: ----------------------------------------
- [13:54:51]: --- Step: Scan ---
- [13:54:51]: ----------------------------------------
+ [13:54:51]: ----------------------------------------
+ [13:54:51]: --- Step: Test package Okapi for iOS ---
+ [13:54:51]: ----------------------------------------
```
> Improved support for custom `destination`, allow custom step name

- Fastlane/provisioning_lanes.rb
- Fastlane/testing_lanes.rb
Our provisioning lanes now support signing macOS apps as well. We've had to reuse the same lanes but with a specific platform set to `macos`. A new environment variable allows configuring `macos` platform specific bundle identifiers.
> Add macOS Support to Fastlane Match

- Fastlane/deployment_lanes.rb
Related to [TMOB-2510].
This PR unshallow the git history before merging a release. This is a solution we (@neodym, @kairadiagne and me) agreed upon in our investigation.
[TMOB-2510]: https://wetransfer.atlassian.net/browse/TMOB-2510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Unshallow git history before merging a release

- Fastlane/deployment_lanes.rb
- Fastlane/provisioning_lanes.rb
We need the lane for setting up Xcode on CI for unit testing our Mac tests.
> Make certs lane public

- Fastlane/deployment_lanes.rb
When we do a hotfix we need to target main instead of develop. Otherwise, it can't generate the changelog.
> Make target branch configurable

- Fastlane/deployment_lanes.rb
We no longer need it; in fact:
> Remove unshallow check

- Fastlane/deployment_lanes.rb
Hopefully, we no longer need this for future releases. We added this in https://github.com/WeTransfer/WeTransfer-iOS-CI/pull/226/files, but it caused files that we moved to return back in this PR: https://github.com/WeTransfer/Mule/pull/2504/files
Let's remove it and see how our next release will go.
> Revert unrelated history argument

- Bitrise/testing_bitrise.yml
Since we're adding more and more tests, it could be possible for our test suite to run over 40 minutes when testing the Mac, iOS, and packages. Increase timeout to 1 hour, which will be enough for regular runs, but prevents hangs to run extendedly.
> Increasing test timeout

- Bitrise/Scripts/pr_labels_testing.sh
- Bitrise/testing_bitrise.yml
Uploading the Simulator build can take up to 30 seconds, while we barely use it. I've now made it optional, but still possible. You can let CI generate a Simulator build by adding the `create-simulator-build` label.
> Only create a Simulator build if the label exists

- Bitrise/testing_bitrise.yml
- WeTransferPRLinter/Sources/WeTransferPRLinter/WeTransferPRLinter.swift
- WeTransferPRLinter/Tests/WeTransferPRLinterTests/WeTransferLinterTests.swift
Danger is and should be a required check on our repositories. However, we can still optimize by skipping steps related to tests based on our configured environment variable.
Secondly, we can benefit from Danger running by posting a message informing us there are no expectations in terms of test results. This makes it clearer Bitrise actually skipped danger with sound reasoning, not because of a build failure.
> Re-enable Danger as its a required check

- Bitrise/Scripts/configure_environment_for_pr.sh
Somehow this change didn't made it in https://github.com/WeTransfer/WeTransfer-iOS-CI/pull/234. Needed to ensure we run tests if swift files are found.
> Update env key to SKIP_TESTS

- README.md
- WeTransferPRLinter/Package.swift
- WeTransferPRLinter/Sources/WeTransferPRLinter/XCResultReporting/ResultItems/TestSummaries.swift
- WeTransferPRLinter/Tests/WeTransferPRLinterTests/XCResultSummaryReporterTests.swift
Adds a new Danger message sharing the top 3 slowest tests. Only tests with a duration above 1 second will be evaluated.
> [Danger] Report slow tests

- Fastlane/shared_lanes.rb
This PR will modifier our error handler to not report on lanes that start with "test".
For example: `:test`, `:test_package`, `:test_sdk`.
> Do not report on lanes that start with "test"

- Bitrise/testing_bitrise.yml
- WeTransferPRLinter/Sources/WeTransferPRLinter/WeTransferPRLinter.swift
- WeTransferPRLinter/Tests/WeTransferPRLinterTests/WeTransferLinterTests.swift
- WeTransferPRLinter/Tests/WeTransferPRLinterTests/XCResultSummaryReporterTests.swift
> Bitrise Pipeline support & Local Running improvements

- Fastlane/provisioning_lanes.rb
After adding a device it would only generate a provisioning profile for the main app. However, we also needed to generate new profiles for the app extensions. This PR fixes that issue.
> Generate provisioning profile for multiple apps using sign lane

- Fastlane/deployment_lanes.rb
One of the properties got renamed to `--use-github-release-notes`.
> Use updated property name for GitBuddy

- Fastlane/deployment_lanes.rb
Don't ask me why, but the `**` needed to be added. I investigated the use of our code and compared it with Fastlane's code. I found out this was the difference.
I could reproduce the failure locally and solved it this way 🚀
> Ruby 3.2.2 broke our CI, using double asterisk we solve this

- Fastlane/deployment_lanes.rb
Before this change, we had a changelog looking as follows:
Not super readable. We decided to improve this, resulting in the following changelog from now on:
```
* Tracking for `accessibilityPerformEscape` for the feature discovery modal by @peagasilva
* Update marketing version to `2.0.2` by @kairadiagne
* fix unit tests by @swaan-miller
* [Cellular Settings] remove toggle by @swaan-miller
* Temporarily add fallback creative ads response locally by @peagasilva
* Add tracking for when the modal is dismissed interactively by @peagasilva
* [Cellular Settings] create settings view by @swaan-miller
* [Send flow] Make the whole Files + > a button by @BasThomas
* [Mac App] Adjust statusbar icon for Menu Bar appearance by @AvdLee
* [Live Activity]: Adding alerts by @neodym
* Mobile Ads - Update …
```
> [TMOB 3481] Improve readability of changelogs

- BuildTools/.swiftlint.yml
Enables https://github.com/WeTransfer/Mule/pull/3302.
This PR updates both SwiftLint rules to include `deinit` closer to `init`.
This PR fixes [TMOB-1798].
[TMOB-1798]: https://wetransfer.atlassian.net/browse/TMOB-1798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update SwiftLint rules

- Fastlane/deployment_lanes.rb
After we've been running into issues with our last screenshots update, I decided to revisit the flow and wrote this documentation:
https://www.notion.so/wetransfer/Update-App-Store-Metadata-Screenshots-75ec032045174dbd911623ee87565452
Part of it is that we will no longer wait for the CI release train to update screenshots and have the risk of our release train failing due to screenshot issues. Instead, we will manually update screenshots locally using `fastlane deliver_screenshots`. 
In fact, you only have to update the screenshots once, and it's a much better workflow to verify uploaded screenshots while updating.
This means that we can now skip screenshots during our CI release train.
Fixes [TMOB-4115]
[TMOB-4115]: https://wetransfer.atlassian.net/browse/TMOB-4115?atlOrigin=eyJpIjoiNWRkN …
> Make sure we don't update screenshots during our release workflow

- Fastlane/testing_lanes.rb
Allows testing using a test plan instead of a scheme.
> Add a scan option for test plans

- BuildTools/.swiftlint.yml
We quite often disable this rule in the project because it can be useful to structure our models. It felt like it's worth removing this rule since we're not respecting it everywhere.
https://github.com/WeTransfer/Mule/pull/3355
> Remove "nesting" rule from .swiftlint.yml

- Fastlane/deployment_lanes.rb
This PR updates the `git diff` command used in CI to list the changes.
The updated command uses the `--no-pager` option, to avoid Git being piped into a pager - more information [here](https://git-scm.com/docs/git/2.43.0).
It also updates the command to use the `--name-status` option, which will give us more information about the changes in the list - more information [here](https://git-scm.com/docs/git-status#_changed_tracked_entries).
Lastly, it diffs the last tag against `HEAD` instead, so it will give us the new changes.
| Before | After |
:---: | :---:
| <img width=200 src="https://github.com/WeTransfer/WeTransfer-iOS-CI/assets/5387088/4a4a6197-bbf4-40c0-8f5a-e9e43b962afd" /> | <img width=400 src="https://github.com/WeTransfer/WeTransfer-iOS-CI/assets/5387088/4c4a50b7-00d2-4dcd-a6f8-c …
> Update `git diff` command

- bitrise.yml
This PR updates the machine type to use M1 instead of Intel. [Bitrise will no longer support Intel machines](https://discuss.bitrise.io/t/macos-intel-machine-type-spring-cleaning-on-the-3rd-of-june/24043).
> Update machine type to M1

- BuildTools/.swiftformat
As per title, exclude the BSP monorepo submodule introduced by [#4313](https://github.com/WeTransfer/Mule/pull/4313) on `Mule` so that the pre-commit hook doesn't format it each time
> Exclude `ios-libs-monorepo` submodule in `.swiftformat`

- Fastlane/provisioning_lanes.rb
As per title, ensure we also fetch the installer distribution certificate and sync it via Match when running provisioning lanes, so that we can do custom distributions from Xcode to ASC of the Mac app
> Fetch Mac installer distribution certificate via Match
