SwiftLint/.swiftlint-source.yml
**Breaking change** fixed typo in rule identifier (~~`nslog_prohibted`~~  `nslog_prohibited`) and removed any references to internal projects
=> Fix log based warnings

Scripts/travis.sh
This allows certain characters (like spaces) in project and scheme name
=> Quote fastlane arguments

Danger/Dangerfile, Danger/ext/git_swift_linter.rb, spec/git_swift_linter_spec.rb
=> Add changelog check, use linter methods

Danger/ext/git_swift_linter.rb, spec/git_swift_linter_spec.rb
We were using `git` instead of `github`
=> Fix github reference

Danger/Dangerfile
This makes use of the new test results file format
=> Fix for Xcode 11

Danger/.rubocop.yml, Danger/Dangerfile, Danger/ext/git_swift_linter.rb, SwiftLint/.swiftlint-source.yml, SwiftLint/.swiftlint-tests.yml, spec/git_swift_linter_spec.rb
As I was fixing CI for https://github.com/AvdLee/appstoreconnect-swift-sdk/pull/54 I had to do several improvements.
=> Several fixes and improvements needed for Open Source projects

Bitrise/testing_bitrise.yml, Danger-Swift/Sources/WeTransferPRLinter/WeTransferPRLinter.swift, Danger-Swift/Tests/WeTransferPRLinterTests/WeTransferLinterTests.swift, Fastlane/Fastfile
=> Fix excluding all test targets for code coverage, SPM testing fixes

Danger-Swift/Package.swift, Danger-Swift/Sources/WeTransferPRLinter/CoverageReporter.swift, Danger-Swift/Sources/WeTransferPRLinter/SwiftLintExecutor.swift, Danger-Swift/Sources/WeTransferPRLinter/WeTransferPRLinter.swift, Danger-Swift/Sources/WeTransferPRLinter/XcodeSummaryReporter.swift, Danger-Swift/Tests/WeTransferPRLinterTests/TestHelpers/DangerTestExtensions.swift, Danger-Swift/Tests/WeTransferPRLinterTests/TestHelpers/Mocks.swift, Danger-Swift/Tests/WeTransferPRLinterTests/TestHelpers/TestXcodeSummaryJSON.swift, Danger-Swift/Tests/WeTransferPRLinterTests/WeTransferLinterTests.swift, Danger-Swift/Tests/WeTransferPRLinterTests/XCTestManifests.swift, SwiftFormat/.swiftformat, SwiftLint/.swiftlint-source.yml, SwiftLint/.swiftlint-tests.yml
Hoo boy, hold on to your hats! A big PR with lots of changes. It's all just formatting though. Closes #77.
(edit: well actually this one isn't that large haha)
=> SwiftFormat

SwiftLint/.swiftlint-source.yml
As discussed in https://github.com/WeTransfer/Mule/pull/372.
=> Added multiline_function_chains rule

Dangerfile.swift
Needed for the new BuildTools folder
=> Update Danger for new SwiftLint config location

BuildTools/.swiftlint-tests.yml
=> Add xct_specific_matcher rule

WeTransferPRLinter/Sources/WeTransferPRLinter/WeTransferPRLinter.swift, WeTransferPRLinter/Sources/WeTransferPRLinter/XCResultReporting/Extensions/ErrorExtensions.swift, WeTransferPRLinter/Tests/WeTransferPRLinterTests/WeTransferLinterTests.swift
Just a little improvement in the Danger messaging.
Fixes #102
=> Make sure to not report a warning if no tests were found

WeTransferPRLinter/Sources/WeTransferPRLinter/XCResultReporting/ResultItems/IssueSummaries.swift, WeTransferPRLinter/Sources/WeTransferPRLinter/XCResultReporting/ResultItems/TestSummaries.swift, WeTransferPRLinter/Tests/WeTransferPRLinterTests/XCResultSummaryReporterTests.swift
To be aware of tests that were retried, we will now get a warning for a retried test.
=> [Danger] Show warning for retried test

Package.swift
Our requested fix was released: https://github.com/danger/swift/releases/tag/3.12.3
=> Update danger to fix CI

WeTransferPRLinter/Sources/WeTransferPRLinter/WeTransferPRLinter.swift
Forgot to add a little filter and decided to optimise the code a bit at the same time.
=> Make sure to filter out spm build warnings in Danger

Fastlane/deployment_lanes.rb
This PR can be merged once a new release becomes available after merging in https://github.com/WeTransfer/GitBuddy/pull/71
We're now outputting the release metadata as JSON which allows us to reuse the existing changelog information. Especially for big releases this means less GitHub API usage as we would otherwise fetch all related issues and PRs twice: once for the changelog and once for the GitHub release.
Part of #86
=> Reuse changelog created at release

BuildTools/Mintfile
=> Bump SwiftFormat & SwiftLint version

BuildTools/swiftformat.sh, BuildTools/swiftlint.sh
Both scripts now handle paths in the same way.
=> Consistent path handling

Fastlane/Fastfile, Fastlane/deployment_lanes.rb
Use `mint run --silent` so it doesn't change the output
=> Fix mint run gitbuddy

Bitrise/testing_bitrise.yml
Closes [TMOB-79](https://wetransfer.atlassian.net/browse/TMOB-79) and allows https://github.com/WeTransfer/Mule/pull/1727.
=> TMOB-79: Add script to assign PR author in the `wetransfer_pr_testing` workflow

Fastlane/shared_lanes.rb
This PR will update the emoji used for information level slack messages.
Old: 🔵
New: ℹ️
=> Emoji update for information slack messages

Fastlane/shared_lanes.rb
This PR will create a shared error handling function for all external projects to use.
=> Making error handling a shared function

Fastlane/shared_lanes.rb
Fixes additional payload handling on slack messages send via CI.
-> I "love" how ruby doesn't check the code before execution... 🤦‍♂️
=> Fixes additional payload handling on slack messages send via CI

Bitrise/Scripts/configure_environment_for_pr.sh, Bitrise/Scripts/setup_environment.sh, Bitrise/testing_bitrise.yml
If the PR under test doesn't contain any `.swift` files, we can skip both Danger and Fastlane related steps.
=> Skip Tests and Danger if no Swift files

Fastlane/deployment_lanes.rb
Updating our deployment lanes to generate changelogs using GH automated changelog generation.
=> Make use of GitBuddy's new release notes

Bitrise/tag_releasing_bitrise.yml, Bitrise/testing_bitrise.yml
Unblocks https://github.com/WeTransfer/Mule/pull/4017.
This PR updates fastlane to be run through bundler.
=> Update fastlane to run through bundler

Bitrise/testing_bitrise.yml, Package.resolved, Package.swift, bitrise.yml
update bitrise settings & danger version
=> Xcode 16 branch
